"""phase 17 add recipes.cuisine

Revision ID: 28b96e0a0f38
Revises: 1aa0511c032b
Create Date: 2026-06-28 15:09:06.342107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b96e0a0f38'
down_revision = '1aa0511c032b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###
