"""recipes.time_band (Phase 18, display-only)

Revision ID: 3cf0d701e765
Revises: 28b96e0a0f38
Create Date: 2026-06-28 19:38:52.367203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf0d701e765'
down_revision = '28b96e0a0f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_band', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('time_band')

    # ### end Alembic commands ###
