"""Phase 11: add generations.meal_type

Revision ID: 795529a081b0
Revises: d1e5859755c5
Create Date: 2026-06-25 17:06:58.735287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795529a081b0'
down_revision = 'd1e5859755c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###
