"""per-user favourites

Revision ID: c4791dc000fe
Revises: 63280aee157f
Create Date: 2026-06-19 14:55:50.771505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4791dc000fe'
down_revision = '63280aee157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_favourite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favourite', sa.BOOLEAN(), nullable=False, server_default=sa.false()))

    op.drop_table('recipe_favourites')
    # ### end Alembic commands ###
