"""add intro and tips_json to recipe

Revision ID: d1e5859755c5
Revises: c4791dc000fe
Create Date: 2026-06-20 19:29:12.671607

Phase 4b: richer recipe output. recipes.intro (energetic context paragraph) and
recipes.tips_json (optional [{title, text}]). Both nullable, so existing rows
take NULL — no backfill needed. Matches create_all in models.py.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e5859755c5'
down_revision = 'c4791dc000fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tips_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('tips_json')
        batch_op.drop_column('intro')

    # ### end Alembic commands ###
