"""Phase 12: add generations.status (async generation)

Revision ID: f3c9a72b4e10
Revises: 795529a081b0
Create Date: 2026-06-26 06:30:00.000000

Adds the single nullable `status` column to `generations` ("running" | "done" |
"error"). Additive and backward-safe: existing rows backfill to NULL, which the
app treats as "done" everywhere, so historical generations still render.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c9a72b4e10'
down_revision = '795529a081b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
